SWII6_TP04/Models/ErrorViewModel.cs
namespace SWII6_TP04.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SWII6_TP04/Controllers/CarrosController.cs
using Microsoft.AspNetCore.Mvc;
using SWII6_TP04.Services;
using SWII6_Models.Dtos;

namespace SWII6_TP03.Controllers;

public class CarrosController : Controller
{
    private readonly CarroService _carroService;

    public CarrosController(CarroService carroService)
    {
        _carroService = carroService;
    }

    // GET: Carros
    public async Task<IActionResult> Index()
    {
        var carros = await _carroService.GetAll();
        return View(carros);
    }

    // GET: Carros/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
            return NotFound();

        var carro = await _carroService.Get((int)id);
        return View(carro);
    }

    // GET: Carros/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Carros/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(CarroCreateDTO carro)
    {
        if (ModelState.IsValid)
        {
            await _carroService.Create(carro);
            return RedirectToAction(nameof(Index));
        }

        return View(carro);
    }

    // GET: Carros/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
            return NotFound();

        var carro = await _carroService.Get((int)id);

        if (carro == null)
            return NotFound();

        return View(carro);
    }

    // POST: Carros/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, CarroUpdateDTO carro)
    {
        if (id != carro.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            await _carroService.Update(carro);
            return RedirectToAction(nameof(Index));
        }
        return View(carro);
    }

    // GET: Carros/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
            return NotFound();

        var carro = await _carroService.Get((int)id);

        if (carro == null)
            return NotFound();

        return View(carro);
    }

    // POST: Carros/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var carro = await _carroService.Get(id);
        if (carro != null)
        {
            await _carroService.Delete(carro.Id);
        }
        
        return RedirectToAction(nameof(Index));
    }
}

SWII6_TP04/Controllers/CreditosController.cs
using Microsoft.AspNetCore.Mvc;

namespace SWII6_TP03.Controllers;

public class CreditosController : Controller
{

    // GET: Creditos
    public async Task<IActionResult> Index()
    {
        return View();
    }
}

SWII6_TP04/Views/Carros/Create.cshtml
@model SWII6_Models.Models.Carro

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Carro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Placa" class="control-label"></label>
                <input asp-for="Placa" class="form-control" />
                <span asp-validation-for="Placa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SWII6_TP04/Views/Carros/Delete.cshtml
@model SWII6_Models.Models.Carro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Carro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Placa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Placa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SWII6_TP04/Views/Carros/Details.cshtml
@model SWII6_Models.Models.Carro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Carro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Placa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Placa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ano)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ano)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SWII6_TP04/Views/Carros/Edit.cshtml
@model SWII6_Models.Models.Carro

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Carro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Placa" class="control-label"></label>
                <input asp-for="Placa" class="form-control" />
                <span asp-validation-for="Placa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ano" class="control-label"></label>
                <input asp-for="Ano" class="form-control" />
                <span asp-validation-for="Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SWII6_TP04/Views/Carros/Index.cshtml
@model IEnumerable<SWII6_Models.Models.Carro>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Placa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ano)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Marca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Placa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ano)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

SWII6_TP04/Views/Creditos/Index.cshtml
<h1>Desenvolvido por Pedro Henrique Botelho Lima</h1>

SWII6_TP04/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SWII6_TP04</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SWII6_TP04.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                SWII6_TP04
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carros" asp-action="Index">Carros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Creditos" asp-action="Index">Creditos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SWII6_TP04
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>